### PR TITLE
fix(ci): install dependencies before Hermes Vitest

### LINKED ISSUE #6143: ci(main): install dependencies before Hermes secret-boundary Vitest
## Summary

`CI / Main` consistently fails in `sandbox-images-and-e2e / build-hermes-sandbox-image` because the workflow invokes the Hermes sandbox secret-boundary Vitest test before setting up Node and installing the repository dependencies.

The Hermes production image itself builds successfully. The failure occurs afterward, while Vitest is loading its configuration.

Related umbrella: #5919

## Evidence

- Failing main run: https://github.com/NVIDIA/NemoClaw/actions/runs/28545735383
  - Attempt 1 failed in `Run Hermes sandbox secret boundary test`.
  - A manual rerun (attempt 2) reproduced the same failure.
- The immediately preceding main run failed the same way: https://github.com/NVIDIA/NemoClaw/actions/runs/28542880649

Representative log:

```text
npm warn exec The following package was not found and will be installed: vitest@4.1.9
Could not resolve 'vitest/config' in vitest.config.ts
Error: Cannot find module 'vitest/config'
```

## Root cause

In `.github/workflows/sandbox-images-and-e2e.yaml`, the relevant steps currently run in this order:

1. Build Hermes production image
2. Verify sandbox user can read copied files
3. Run Hermes sandbox secret boundary test with `npx vitest`
4. Set up Node
5. Install root dependencies with `npm ci --ignore-scripts`
6. Run Hermes root entrypoint smoke Vitest test

On a clean hosted runner, step 3 has no local Vitest installation. `npx` downloads an isolated package, but the repository's `vitest.config.ts` cannot resolve `vitest/config` from the absent root `node_modules`.

The ordering regression was introduced by #5756 / commit `8120223922bf`: the secret-boundary lane changed from a standalone shell test to Vitest, but the existing Node setup and dependency installation remained below it.

This is not caused by #6109. That PR did not modify the workflow or Hermes code, and the parent main commit reproduced the same failure.

## Proposed fix

Move the existing `Set up Node` and `Install root dependencies` steps before the first Vitest invocation, so both Hermes Vitest tests use the repository's pinned dependency set:

1. Check out repository
2. Set up Node
3. Install root dependencies
4. Build and verify Hermes production image
5. Run Hermes sandbox secret-boundary Vitest test
6. Run Hermes root-entrypoint smoke Vitest test

## Acceptance criteria

- A clean `CI / Main` runner does not print the `npx` ad-hoc Vitest installation warning.
- `hermes-sandbox-secret-boundary.test.ts` loads `vitest.config.ts` successfully and executes.
- `hermes-root-entrypoint-smoke.test.ts` continues to execute with the same installed dependencies.
- The `build-hermes-sandbox-image` job passes on a fresh hosted runner.

### PR DESCRIPTION
**Pull request by apurvvkumaria**
## Summary
Move Node setup and the locked root dependency install ahead of the first Hermes Vitest invocation so clean runners resolve the repository's pinned `vitest/config`. Add a workflow contract test to prevent the ordering regression.

## Related Issue
Fixes #6143

## Changes
- Run the pinned `actions/setup-node` step before the Hermes image tests.
- Run `npm ci --ignore-scripts` before both Hermes Vitest invocations.
- Add a workflow contract test that enforces the setup and install ordering for both test steps.

## Type of Change

- [x] Code change (feature, bug fix, or refactor)
- [ ] Code change with doc updates
- [ ] Doc only (prose changes, no code sample modifications)
- [ ] Doc only (includes code sample changes)

## Quality Gates
- [x] Tests added or updated for changed behavior
- [ ] Existing tests cover changed behavior — justification:
- [ ] Tests not applicable — justification:
- [ ] Docs updated for user-facing behavior changes
- [x] Docs not applicable — justification: Internal CI step ordering only; no user-facing behavior changes.
- [ ] Sensitive paths changed (security, policy, credentials, preflight, onboarding, inference, runner, sandbox, or messaging)
- [ ] Sensitive-path review completed or maintainer-approved waiver recorded — reviewer/approval link/justification:
- [ ] Non-success, skipped, or missing CI check accepted by maintainer — check name, approval link, and follow-up issue:

## Verification
- [x] PR description includes the DCO sign-off declaration and every commit appears as `Verified` in GitHub
- [ ] Git hooks passed during commit and push, or `npx prek run --from-ref main --to-ref HEAD` passes
  - Changed-file pre-commit checks and the normal pre-push hook passed. The diff-scoped fallback reaches unrelated existing macOS filesystem-permission failures in the broad integration suite.
- [x] Targeted tests pass for changed behavior
  - `npx vitest run --project integration test/hermes-sandbox-workflow.test.ts` (1 test passed)
- [ ] Full `npm test` passes (broad runtime changes only)
- [x] Quality Gates section completed with required justifications or waivers
- [x] No secrets, API keys, or credentials committed
- [ ] `npm run docs` builds without warnings (doc changes only)
- [ ] Doc pages follow the [style guide](https://github.com/NVIDIA/NemoClaw/blob/main/docs/CONTRIBUTING.md) (doc changes only)
- [ ] New doc pages include SPDX header and frontmatter (new pages only)

---
Signed-off-by: Apurv Kumaria <36614+apurvvkumaria@users.noreply.github.com>

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved the order of setup and dependency installation in the Hermes sandbox workflow, helping the pipeline run more reliably.
  * Added automated checks to prevent regressions in workflow step ordering and command configuration.

### CODE REVIEW

**Comment by wscurran** [comment]
✨ Thanks for the fix. This addresses the CI workflow ordering issue for Hermes Vitest tests with a contract test to prevent regression.

---
**Related open issues:**
- [#6143 ci(main): install dependencies before Hermes secret-boundary Vitest](https://github.com/NVIDIA/NemoClaw/issues/6143)

**Review by prekshivyas — APPROVED** [review]
