### ISSUE TITLE
build: recorded messaging reconciliation omits required dependencies

### ISSUE THREAD

**Issue by deepujain** [NVIDIA/NemoClaw#9359]
## Description

Current main does not compile after #9296. `selectionFromRecordedChannels` calls `filterUnconfiguredHostChannelsFromSelection(selection, options.agent)`, but the helper now requires the dependency object as its third argument.

## Reproduction

```text
$ npm run build:cli
src/lib/onboard/machine/handlers/sandbox-messaging.ts(389,15): error TS2554: Expected 3 arguments, but got 2.
```

The same failure appears in #9296's post-merge `build-typecheck` and CLI shard checks.

## Expected behavior

The recorded-channel reconciliation path passes `options.deps` so the helper can persist or clear the filtered plan and report the retired channel.

## Proposed fix

Pass `options.deps` at the call site and add a focused regression assertion for the recorded-channel path.

## Checklist

- [x] Reproduced on current main at `183a9c8760`
- [x] Searched open issues and PRs for the helper and compiler error
