### PR TITLE
fix(onboard): pass messaging dependencies during reuse

### LINKED ISSUE #9359: build: recorded messaging reconciliation omits required dependencies
## Description

Current main does not compile after #9296. `selectionFromRecordedChannels` calls `filterUnconfiguredHostChannelsFromSelection(selection, options.agent)`, but the helper now requires the dependency object as its third argument.

## Reproduction

```text
$ npm run build:cli
src/lib/onboard/machine/handlers/sandbox-messaging.ts(389,15): error TS2554: Expected 3 arguments, but got 2.
```

The same failure appears in #9296's post-merge `build-typecheck` and CLI shard checks.

## Expected behavior

The recorded-channel reconciliation path passes `options.deps` so the helper can persist or clear the filtered plan and report the retired channel.

## Proposed fix

Pass `options.deps` at the call site and add a focused regression assertion for the recorded-channel path.

## Checklist

- [x] Reproduced on current main at `183a9c8760`
- [x] Searched open issues and PRs for the helper and compiler error

### PR DESCRIPTION
**Pull request by deepujain**
## Summary

Restore the recorded messaging resume path after the lifecycle reconciliation update. Recorded channels now pass the required persistence and notification dependencies into host-channel filtering, and the affected reuse fixtures model that contract.

## Related Issue

Fixes #9359

## Changes

- Pass onboarding messaging dependencies through recorded-channel reconciliation.
- Update the existing reuse fixtures to provide the dependency contract required when channels are filtered and persisted.

## Type of Change

- [x] Code change (feature, bug fix, or refactor)
- [ ] Code change with doc updates
- [ ] Doc only (prose changes, no code sample modifications)
- [ ] Doc only (includes code sample changes)

## Quality Gates

- [x] Tests added or updated for changed behavior
- [ ] Existing tests cover changed behavior — justification:
- [ ] Tests not applicable — justification:
- [x] Sensitive paths changed (security, policy, credentials, preflight, onboarding, inference, runner, sandbox, or messaging)
- [ ] Sensitive-path review completed or maintainer-approved waiver recorded — reviewer/approval link/justification:
- [ ] Non-success, skipped, or missing CI check accepted by maintainer — check name, approval link, and follow-up issue:

## DGX Station Hardware Evidence

- [ ] Tested on DGX Station
- Tested commit: Not applicable
- Station profile/scenario: Not applicable
- Result: Not applicable
- Supporting evidence: Not applicable

## Verification

- [x] PR description includes a `Signed-off-by:` line and every commit appears as `Verified` in GitHub
- [x] Normal `pre-commit`, `commit-msg`, and `pre-push` hooks passed, or `npm run validate:pr` passed after refreshing `origin/main` when hooks were skipped or unavailable
- [x] Targeted behavior tests pass for the current change set, or tests are marked not applicable above — `npx vitest run --project cli src/lib/onboard/machine/handlers/sandbox-messaging.test.ts` (32 passed)
- [ ] Applicable broad gate passed — `npm test` for broad runtime/test-harness changes; `npm run check` for repo-wide validation/coverage changes — command/result:
- [x] Quality Gates section completed with required justifications or waivers
- [x] No secrets, API keys, or credentials committed
- [ ] `npm run docs` builds without warnings (doc changes only)
- [ ] Doc pages follow the [style guide](https://github.com/NVIDIA/NemoClaw/blob/main/docs/CONTRIBUTING.md) (doc changes only)
- [ ] New doc pages include SPDX header and frontmatter (new pages only)

Additional validation: `npm run build:cli`, `npm run typecheck:cli`, and `npm run lint`.

---
Signed-off-by: Deepak Jain <deepujain@gmail.com>

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved reconciliation when resuming recorded sandbox messaging sessions.
  * Missing host configuration is now clearly noted, while outdated saved plans are removed without being rewritten.
  * Improved filtering of unavailable messaging channels and handling of related plan updates and notifications.

### CODE REVIEW

**Comment by deepujain** [comment]
Added focused assertions for the recorded-channel side effects and documented the reconciliation helper. The targeted suite, typecheck, lint, and repository checks pass.

**Review by prekshivyas — APPROVED** [review]
