### ISSUE TITLE
build-typecheck broken on main: duplicate `readinessComparisonMatches` in serving/resolver.ts (TS2393)

### ISSUE THREAD

**Issue by yanyunl1991** [NVIDIA/NemoClaw#8438]
## Summary

`build-typecheck` fails on `main` because `src/lib/inference/serving/resolver.ts` defines the function `readinessComparisonMatches` **twice**, which `tsc` rejects:

```
src/lib/inference/serving/resolver.ts(203,10): error TS2393: Duplicate function implementation.
src/lib/inference/serving/resolver.ts(247,10): error TS2393: Duplicate function implementation.
```

This is a compile error, so it blocks `build-typecheck` and everything that depends on the build — `cli-test-shards (1..7)`, `installer-integration`, `static-checks`, and the E2E gates all go red as a cascade. It reproduces on a clean checkout of `main` (HEAD `ce9d1740f`) with `npm run typecheck:cli`, and on any PR whose merge base includes it (e.g. it currently reds out unrelated PRs).

## The two definitions differ

They are **not** identical duplicates — they diverge in the `version-at-least` branch, so this looks like a bad merge where the old and new implementations both survived:

- First definition (~line 203):
  ```ts
  case "version-at-least":
    return versionAtLeast(actual, comparison.value);
  ```
- Second definition (~line 247):
  ```ts
  case "version-at-least": {
    if (typeof actual !== "string") return false;
    const order = compareNumericDottedVersions(actual, comparison.value);
    return order !== undefined && order >= 0;
  }
  ```

Because the two versions have different behavior, the correct fix is to keep whichever `version-at-least` implementation is intended (the `compareNumericDottedVersions` one appears to be the newer intent) and delete the other — that call belongs to the serving-profile owners, so flagging rather than patching.

## Likely origin

Recent commits touching this file, most-recent first: #8391 (`fix(inference): honor host-local serving recipe contracts`), #8402 (`fix(inference): admit remediable Spark storage`), #8399 (`feat(inference): add fixed local serving profiles`). The duplicate most likely landed in that series.

## Impact

Repo-wide CI red on `main` and on PRs based on it — no PR built on this base can go green until the duplicate is removed.

**Comment by yanyunl1991** [comment]
Extra data point for whoever resolves this: the two definitions are behaviorally different, so it is not a "delete either one" fix.

Removing the **first** definition (the `versionAtLeast` variant) and keeping the second (`compareNumericDottedVersions`) makes the build compile, but then one inference test fails:

```
FAIL src/lib/inference/serving/resolver.test.ts > managed inference resolver
  > admits a storage conflict that the public lifecycle can remediate (#8246)
AssertionError: expected { outcome: 'rejected', … } to match object { outcome: 'selected', … }
```

So the `version-at-least` semantics differ between the two copies and the surviving one must be chosen deliberately (and the `#8246` test kept green). Flagging for the serving-profile owners rather than patching.

**Comment by JulienAu** [comment]
Verified on current `main`: `readinessComparisonMatches` now has a single definition in `src/lib/inference/serving/resolver.ts`, so the TS2393 duplicate no longer reproduces. Looks like the fix landed without closing this issue; it can probably be closed.

**Comment by erensh27** [comment]
This is already resolved on main: `src/lib/inference/serving/resolver.ts` now contains a single `readinessComparisonMatches` implementator (the `compareMumericDottedVersions` version), and `npm run typecheck:cli` passes on HEAD. No further change needed.

**Comment by VishnuR23** [comment]
This looks resolved on current `main`.

`src/lib/inference/serving/resolver.ts` now declares `readinessComparisonMatches` once, at line 217, and calls it at line 250. There is no second declaration, so the TS2393 duplicate-identifier error no longer reproduces.

`npm run typecheck:cli` completes with exit code 0 on `6f4ff97`, and the `build-typecheck` job passes on current pull requests.

Reporting rather than closing, since I am not a maintainer and cannot tell from here whether you want to keep this open to track a regression test.
