### ISSUE TITLE
ci(main): install dependencies before Hermes secret-boundary Vitest

### ISSUE THREAD

**Issue by apurvvkumaria** [NVIDIA/NemoClaw#6143]
## Summary

`CI / Main` consistently fails in `sandbox-images-and-e2e / build-hermes-sandbox-image` because the workflow invokes the Hermes sandbox secret-boundary Vitest test before setting up Node and installing the repository dependencies.

The Hermes production image itself builds successfully. The failure occurs afterward, while Vitest is loading its configuration.

Related umbrella: #5919

## Evidence

- Failing main run: https://github.com/NVIDIA/NemoClaw/actions/runs/28545735383
  - Attempt 1 failed in `Run Hermes sandbox secret boundary test`.
  - A manual rerun (attempt 2) reproduced the same failure.
- The immediately preceding main run failed the same way: https://github.com/NVIDIA/NemoClaw/actions/runs/28542880649

Representative log:

```text
npm warn exec The following package was not found and will be installed: vitest@4.1.9
Could not resolve 'vitest/config' in vitest.config.ts
Error: Cannot find module 'vitest/config'
```

## Root cause

In `.github/workflows/sandbox-images-and-e2e.yaml`, the relevant steps currently run in this order:

1. Build Hermes production image
2. Verify sandbox user can read copied files
3. Run Hermes sandbox secret boundary test with `npx vitest`
4. Set up Node
5. Install root dependencies with `npm ci --ignore-scripts`
6. Run Hermes root entrypoint smoke Vitest test

On a clean hosted runner, step 3 has no local Vitest installation. `npx` downloads an isolated package, but the repository's `vitest.config.ts` cannot resolve `vitest/config` from the absent root `node_modules`.

The ordering regression was introduced by #5756 / commit `8120223922bf`: the secret-boundary lane changed from a standalone shell test to Vitest, but the existing Node setup and dependency installation remained below it.

This is not caused by #6109. That PR did not modify the workflow or Hermes code, and the parent main commit reproduced the same failure.

## Proposed fix

Move the existing `Set up Node` and `Install root dependencies` steps before the first Vitest invocation, so both Hermes Vitest tests use the repository's pinned dependency set:

1. Check out repository
2. Set up Node
3. Install root dependencies
4. Build and verify Hermes production image
5. Run Hermes sandbox secret-boundary Vitest test
6. Run Hermes root-entrypoint smoke Vitest test

## Acceptance criteria

- A clean `CI / Main` runner does not print the `npx` ad-hoc Vitest installation warning.
- `hermes-sandbox-secret-boundary.test.ts` loads `vitest.config.ts` successfully and executes.
- `hermes-root-entrypoint-smoke.test.ts` continues to execute with the same installed dependencies.
- The `build-hermes-sandbox-image` job passes on a fresh hosted runner.

**Comment by apurvvkumaria** [comment]
Clarification: #6138 does **not** fix this failure.

#6138 updates the separate `rebuild-hermes` live test to parse the current `v0.17.0`-style Hermes version output. The failure tracked here happens earlier in `build-hermes-sandbox-image`, when `hermes-sandbox-secret-boundary.test.ts` tries to load Vitest before the workflow has installed the repository dependencies.

#6138 does not modify `.github/workflows/sandbox-images-and-e2e.yaml` or dependency setup, so this CI failure will remain until the Node setup and `npm ci --ignore-scripts` steps run before the first Vitest invocation.
