### ISSUE TITLE
test(e2e): fix empty OpenClaw Slack runtime proof

### ISSUE THREAD

**Issue by ericksoa** [NVIDIA/NemoClaw#6467]
## Context

The default `e2e-all` fan-out repeatedly fails `messaging-providers` after OpenClaw returns no channel-list output and the installed Slack runtime proof emits an empty result. The same signature occurs on `main` and on PR #6431, whose DCode-only workflow change does not execute for this independent OpenClaw job.

## Reproduction evidence

- `main` run [28911441118, job 85769533649](https://github.com/NVIDIA/NemoClaw/actions/runs/28911441118/job/85769533649)
- PR #6431 exact-head run [28919686103, attempt 1 job 85794027473](https://github.com/NVIDIA/NemoClaw/actions/runs/28919686103/job/85794027473)
- The same exact-head run, [attempt 2 job 85865912196](https://github.com/NVIDIA/NemoClaw/actions/runs/28919686103/job/85865912196)

All three runs reach the same sequence:

```text
[skip] M6e-M6h: OpenClaw channels list returned no output
installed Slack runtime proof did not emit a valid result:
```

The main and PR artifacts also contain the same underlying OpenClaw Slack loader error:

```text
this[#customizations].loadSync is not a function
```

The empty stdout is then rejected by `parseInstalledSlackProof()` in `test/e2e/live/messaging-providers-slack-runtime-proof.ts`.

## Expected behavior

- `openclaw channels list` emits the expected channel state.
- The installed Slack runtime proof emits a valid structured result.
- If the installed OpenClaw loader is incompatible, the E2E reports the loader failure directly instead of surfacing an empty proof result.

## Acceptance criteria

- [ ] Reproduce and identify the OpenClaw Slack loader/API mismatch on current `main`.
- [ ] Fix the runtime path or proof harness without weakening Slack policy, placeholder, credential, or secret-redaction assertions.
- [ ] Preserve actionable loader diagnostics when the proof subprocess produces no result.
- [ ] Pass `messaging-providers` on two consecutive Ubuntu live E2E runs.

## Related work

- #6022 tracks decomposition of the broad messaging E2E but does not currently own this failure.
- #5896 is the post-tag runtime-proof umbrella from #5595; this specific empty-output defect is not in its enumerated scope.
- The affected installed-runtime proof was introduced by #5595.
